<?php
/** @var string $message */ /** @var array $vendos */ /** @var array $routers */ /** @var bool $canManageVendos */ /** @var string $csrf */
?>
<div class="heading"><div><h1>Vendos</h1><p class="muted">Configure local PisoWiFi coin slots and the hotspot networks where each one is available.</p></div><?php if($canManageVendos):?><button class="button" type="button" data-bs-toggle="modal" data-bs-target="#vendoModal" data-mode="create">Add vendo</button><?php endif;?></div>
<?= $message ?>
<section class="panel"><h2>Configured vendos</h2><p class="muted">Client subnet lets PixiePoint automatically choose the coin slot from the IP MikroTik assigned to the customer.</p><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Name</th><th>Router</th><th>Client subnet</th><th>Interface</th><th>Local URL</th><th>Status</th><?php if($canManageVendos):?><th class="text-end">Action</th><?php endif;?></tr></thead><tbody>
<?php foreach($vendos as $vendo):?><tr><td><strong><?=e($vendo['name'])?></strong></td><td><?=e($vendo['router_name'])?><div class="small text-body-secondary"><?=e($vendo['router_identity'])?></div></td><td class="code"><?=e($vendo['client_subnet']?:'Any')?></td><td><?=e($vendo['interface_name']?:'Any interface')?></td><td class="code"><?=e($vendo['base_url'])?></td><td><span class="badge <?=$vendo['enabled']?'':'off'?>"><?=$vendo['enabled']?'Enabled':'Disabled'?></span></td><?php if($canManageVendos):?><td class="text-end"><button class="btn btn-sm btn-outline-secondary" type="button" data-bs-toggle="modal" data-bs-target="#vendoModal" data-mode="edit" data-id="<?=e($vendo['id'])?>" data-name="<?=e($vendo['name'])?>" data-router="<?=e($vendo['router_id'])?>" data-url="<?=e($vendo['base_url'])?>" data-subnet="<?=e($vendo['client_subnet']??'')?>" data-interface="<?=e($vendo['interface_name']??'')?>" data-password-mode="<?=e($vendo['password_mode'])?>" data-charging="<?=$vendo['charging_enabled']?'1':'0'?>" data-eload="<?=$vendo['eload_enabled']?'1':'0'?>" data-enabled="<?=$vendo['enabled']?'1':'0'?>">Edit</button></td><?php endif;?></tr><?php endforeach;?>
<?php if(!$vendos):?><tr><td colspan="<?=$canManageVendos?7:6?>" class="empty">No vendos configured. Use Add vendo to link your first coin-slot controller.</td></tr><?php endif;?></tbody></table></div></section>
<?php if($canManageVendos):?>
<div class="modal fade" id="vendoModal" tabindex="-1" aria-labelledby="vendoModalTitle" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><form method="post"><div class="modal-header"><div><h2 class="modal-title fs-5 mb-1" id="vendoModalTitle">Add vendo</h2><p class="small text-body-secondary mb-0">Link a coin-slot controller to the MikroTik network where customers can reach it.</p></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body">
<input type="hidden" name="_csrf" value="<?=e($csrf)?>"><input type="hidden" name="action" value="create"><input type="hidden" name="id" value="0"><div class="row g-3">
<div class="col-md-6"><label for="vendo-name">Name</label><input id="vendo-name" name="name" required maxlength="160"><small class="text-body-secondary">Friendly coin-slot name shown to customers and operators.</small></div>
<div class="col-md-6"><label for="vendo-router">Router</label><select id="vendo-router" name="router_id" required><option value="">Select router</option><?php foreach($routers as $router):?><option value="<?=e($router['id'])?>"><?=e($router['name'])?> · <?=e($router['identity'])?></option><?php endforeach;?></select><small class="text-body-secondary">RouterOS identity is matched first when the hosted portal opens.</small></div>
<div class="col-md-6"><label for="vendo-subnet">Client subnet</label><input id="vendo-subnet" name="client_subnet" placeholder="10.0.3.0/24" maxlength="64"><small class="text-body-secondary">IP range MikroTik gives customers using this vendo. PixiePoint uses the customer's IP to auto-select it.</small></div>
<div class="col-md-6"><label for="vendo-url">Local base URL</label><input id="vendo-url" name="base_url" placeholder="http://10.0.3.2" required maxlength="255"><small class="text-body-secondary">Actual local address of this vendo controller. It does not need to match the customer's IP.</small></div>
<div class="col-md-6"><label for="vendo-interface">Interface</label><input id="vendo-interface" name="interface_name" placeholder="Optional, e.g. bridge-HS" maxlength="128"><small class="text-body-secondary">Fallback match when no configured client subnet matches.</small></div>
<div class="col-md-6"><label for="vendo-password">Password mode</label><select id="vendo-password" name="password_mode"><option value="blank">Blank password</option><option value="voucher">Voucher as password</option></select><small class="text-body-secondary">Controls how the voucher authenticates to MikroTik.</small></div>
<div class="col-md-6"><div class="form-check"><input class="form-check-input" type="checkbox" name="charging_enabled" value="1" id="vendo-charging"><label class="form-check-label" for="vendo-charging">Phone charging</label><div class="small text-body-secondary">Show charging controls when supported.</div></div></div><div class="col-md-6"><div class="form-check"><input class="form-check-input" type="checkbox" name="eload_enabled" value="1" id="vendo-eload"><label class="form-check-label" for="vendo-eload">E-load</label><div class="small text-body-secondary">Show e-load controls when supported.</div></div></div>
<div class="col-md-6" id="vendo-enabled-wrap" hidden><div class="form-check"><input class="form-check-input" type="checkbox" name="enabled" value="1" id="vendo-enabled"><label class="form-check-label" for="vendo-enabled">Enabled</label><div class="small text-body-secondary">Disabled vendos are never offered to hotspot clients.</div></div></div></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button><button class="button" type="submit" id="vendo-submit">Add vendo</button></div></form></div></div></div>
<script>document.getElementById('vendoModal').addEventListener('show.bs.modal',function(event){const b=event.relatedTarget,e=b&&b.dataset.mode==='edit',f=this.querySelector('form');f.reset();f.querySelector('[name="action"]').value=e?'update':'create';f.querySelector('[name="id"]').value=e?b.dataset.id:'0';f.querySelector('[name="name"]').value=e?b.dataset.name:'';f.querySelector('[name="router_id"]').value=e?b.dataset.router:'';f.querySelector('[name="base_url"]').value=e?b.dataset.url:'';f.querySelector('[name="client_subnet"]').value=e?b.dataset.subnet:'';f.querySelector('[name="interface_name"]').value=e?b.dataset.interface:'';f.querySelector('[name="password_mode"]').value=e?b.dataset.passwordMode:'blank';f.querySelector('[name="charging_enabled"]').checked=e&&b.dataset.charging==='1';f.querySelector('[name="eload_enabled"]').checked=e&&b.dataset.eload==='1';f.querySelector('[name="enabled"]').checked=e?b.dataset.enabled==='1':true;document.getElementById('vendo-enabled-wrap').hidden=!e;document.getElementById('vendoModalTitle').textContent=e?'Edit vendo':'Add vendo';document.getElementById('vendo-submit').textContent=e?'Save changes':'Add vendo';});</script>
<?php endif;?>
