server {
    listen 80;
    server_name hs.portalx.win;

    # Path visible inside web_nginx
    root /var/www/pixiepoint/public;
    index index.php;

    client_max_body_size 50M;

    location /assets/ {
        try_files $uri =404;
        access_log off;
        expires 7d;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;

        # PHP container
        fastcgi_pass spms_ars_php:9000;

        # IMPORTANT:
        # Path as seen INSIDE spms_ars_php,
        # not the nginx container path.
        fastcgi_param SCRIPT_FILENAME /var/www/pixiepoint/public$fastcgi_script_name;

        fastcgi_index index.php;
    }

    location ~ /\.ht {
        deny all;
    }
}