<?php
/** @var array $router */
/** @var array<string,array{label:string,value:mixed}> $metrics */
/** @var array $recentSessions */
/** @var array $stations */
/** @var array $gatewayVendos */
/** @var array $themes */
/** @var array $portalFeatures */
/** @var bool $canManageRouter */
/** @var bool $canManageStations */
/** @var bool $canManageTeam */
/** @var string $message */
/** @var string $csrf */
$featureLabels=['voucher_login'=>'Voucher','member_login'=>'Member login','trial'=>'Trial / free time','coin_slot'=>'Vendo','qr_scan'=>'QR / scanner','points'=>'Points','points_convert'=>'Convert points','points_play'=>'Play with points','points_share'=>'Share points'];
$featureOn=static fn(string $key):bool=>(bool)($portalFeatures[$key]['value']??in_array($key,['coin_slot','voucher_login'],true));
?>
<div class="heading"><div><div class="d-flex align-items-center gap-2 mb-1"><span class="badge">MikroTik</span><span class="text-body-secondary small">Gateway #<?= e($router['id']) ?></span></div><h1><?= e($router['name']) ?></h1><p class="muted mb-0"><?= e($router['identity']) ?><?php if(!empty($router['location'])): ?> · <?= e($router['location']) ?><?php
endif;?></p></div><div class="actions"><?php if($canManageTeam):?><a class="btn btn-outline-secondary" href="/admin/routers/<?= e($router['id']) ?>/team">Team</a><?php
endif;?><?php if($canManageRouter):?><button class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#routerSettingsModal">Gateway settings</button><button class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#portalFeaturesModal">Access defaults</button><?php
endif;?></div></div>
<?= $message ?>
<section class="grid" aria-label="Gateway summary"><?php foreach($metrics as $metric):?><div class="metric"><small><?= e($metric['label']) ?></small><strong><?= $metric['label']==='Sales today'?'₱'.e(number_format((float)$metric['value'],2)):e((int)$metric['value']) ?></strong></div><?php
endforeach;?></section>
<section class="panel" id="stations">
<div class="d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-2 mb-3"><div><h2 class="mb-1">Hotspot stations</h2><p class="muted mb-0">Each station represents one MikroTik Hotspot network and can be linked to one Vendo.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary" href="/admin/portal-themes">Portal themes</a><a class="btn btn-outline-secondary" href="/admin/vendo-gateway">Vendos</a><?php if($canManageStations):?><button class="button" data-bs-toggle="modal" data-bs-target="#stationModal" data-mode="create">Add station</button><?php
endif;?></div></div>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th>Station</th><th>Network</th><th>Access methods</th><th>Vendo</th><th>Status</th><?php if($canManageStations):?><th></th><?php
endif;?></tr></thead><tbody>
<?php foreach($stations as $s):$settings=$s['feature_settings']??[];
$resolved=$s['resolved_features']??[];?><tr>
<td><strong><?= e($s['name']) ?></strong><div class="small text-body-secondary"><?= e($s['interface_name']?:'Interface not set') ?></div></td>
<td><div class="code"><?= e($s['server_ip']?:'—') ?></div><div class="small text-body-secondary"><?= e($s['client_subnet']?:'No subnet') ?></div></td>
<td><div class="d-flex flex-wrap gap-1"><?php
$shown=0;
foreach($featureLabels as $key=>$label):if(!(bool)($resolved[$key]['enabled']??false))continue;
$shown++;?><span class="badge text-bg-success"><?= e($label) ?></span><?php
endforeach;?><?php if(!$shown):?><span class="text-body-secondary small">None</span><?php
endif;?></div></td>
<td><?php if(!empty($s['vendo_device_id'])):?><div class="fw-semibold"><?= e($s['vendo_name']?:'Vendo') ?></div><div class="small text-body-secondary code"><?= e($s['vendo_device_id']) ?></div><?php
else:?><span class="text-body-secondary">Not linked</span><?php
endif;?><?php if($canManageStations):?><div class="mt-1"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#linkVendoModal" data-station-id="<?= e($s['id']) ?>" data-station-name="<?= e($s['name']) ?>" data-device-id="<?= e($s['vendo_device_id']??'') ?>"><?= !empty($s['vendo_device_id'])?'Change':'Link Vendo' ?></button></div><?php
endif;?></td>
<td><?= $s['enabled']?'<span class="badge text-bg-success">Enabled</span>':'<span class="badge text-bg-secondary">Disabled</span>' ?></td>
<?php if($canManageStations):?><td class="text-end"><div class="d-flex gap-1 justify-content-end"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#featuresModal" data-id="<?= e($s['id']) ?>" data-name="<?= e($s['name']) ?>" data-features='<?= e(json_encode($settings)) ?>'>Access</button><button class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#stationModal" data-mode="edit" data-id="<?= e($s['id']) ?>" data-name="<?= e($s['name']) ?>" data-theme="<?= e($s['portal_theme_id']??0) ?>" data-server-ip="<?= e($s['server_ip']??'') ?>" data-subnet="<?= e($s['client_subnet']??'') ?>" data-interface="<?= e($s['interface_name']??'') ?>" data-password-mode="<?= e($s['password_mode']) ?>" data-enabled="<?= $s['enabled']?'1':'0' ?>">Edit</button></div></td><?php
endif;?>
</tr><?php
endforeach;?><?php if(!$stations):?><tr><td colspan="6" class="empty">No hotspot stations configured.</td></tr><?php
endif;?></tbody></table></div></section>
<?php if($recentSessions):?><section class="panel"><h2>Recent sessions</h2><table><thead><tr><th>Access</th><th>Device</th><th>Status</th><th>Updated</th></tr></thead><tbody><?php foreach($recentSessions as $session):?><tr><td><?= e($session['username']?:'—') ?></td><td class="code"><?= e($session['mac']?:'—') ?></td><td><?= e($session['status']) ?></td><td><?= e($session['updated_at']) ?></td></tr><?php
endforeach;?></tbody></table></section><?php
endif;?>
<?php if($canManageRouter):?>
<div class="modal fade" id="routerSettingsModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="post" action="/admin/routers/<?= e($router['id']) ?>/settings"><div class="modal-header"><h2 class="modal-title fs-5">Gateway settings</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="_csrf" value="<?= e($csrf) ?>"><input type="hidden" name="action" value="router_settings"><div class="row g-3"><div class="col-md-6"><label>Gateway name</label><input name="name" value="<?= e($router['name']) ?>" required></div><div class="col-md-6"><label>RouterOS identity</label><input value="<?= e($router['identity']) ?>" readonly></div><div class="col-md-6"><label>Public hostname / VPN IP</label><input name="public_host" value="<?= e($router['public_host']??'') ?>"></div><div class="col-md-6"><label>Location</label><input name="location" value="<?= e($router['location']??'') ?>"></div><div class="col-md-6"><label>Portal theme</label><select name="portal_theme_id"><option value="0">System default</option><?php foreach($themes as $theme):?><option value="<?= e($theme['id']) ?>" <?= (int)($router['portal_theme_id']??0)===(int)$theme['id']?'selected':'' ?>><?= e($theme['name']) ?></option><?php
endforeach;?></select></div><div class="col-12"><label><input type="checkbox" name="enabled" value="1" <?= $router['enabled']?'checked':'' ?>> Enabled</label></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="button">Save settings</button></div></form></div></div></div>
<div class="modal fade" id="portalFeaturesModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><form method="post" action="/admin/routers/<?= e($router['id']) ?>/settings"><div class="modal-header"><div><h2 class="modal-title fs-5">Default access methods</h2><div class="small text-body-secondary">Inherited by stations unless overridden.</div></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="_csrf" value="<?= e($csrf) ?>"><input type="hidden" name="action" value="portal_features"><div class="row g-3"><?php foreach($featureLabels as $key=>$label):?><div class="col-md-4"><label><input type="checkbox" name="<?= e($key) ?>" value="1" <?= $featureOn($key)?'checked':'' ?>> <?= e($label) ?></label></div><?php
endforeach;?><div class="col-md-4"><label>Trial minutes</label><input type="number" name="trial_minutes" min="1" max="1440" value="<?= e($portalFeatures['trial']['config']['minutes']??10) ?>"></div><div class="col-md-4"><label>Convert points</label><input type="number" name="convert_points" min="1" value="<?= e($portalFeatures['points_convert']['config']['points']??10) ?>"></div><div class="col-md-4"><label>Convert to minutes</label><input type="number" name="convert_minutes" min="1" value="<?= e($portalFeatures['points_convert']['config']['minutes']??5) ?>"></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="button">Save defaults</button></div></form></div></div></div>
<?php
endif;?>
<?php if($canManageStations):?>
<div class="modal fade" id="featuresModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="post" action="/admin/stations"><div class="modal-header"><div><h2 class="modal-title fs-5">Station access methods</h2><div class="small text-body-secondary" id="feature-station-name"></div></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="_csrf" value="<?= e($csrf) ?>"><input type="hidden" name="action" value="save_station_features"><input type="hidden" name="id"><div class="row g-3"><?php foreach($featureLabels as $key=>$label):?><div class="col-md-6"><label><?= e($label) ?></label><select name="<?= e($key) ?>" data-feature="<?= e($key) ?>"><option value="inherit">Inherit gateway</option><option value="on">Enabled</option><option value="off">Disabled</option></select></div><?php
endforeach;?><div class="col-md-4"><label>Trial minutes</label><input type="number" name="trial_minutes" min="1" value="10"></div><div class="col-md-4"><label>Convert points</label><input type="number" name="convert_points" min="1" value="10"></div><div class="col-md-4"><label>Convert to minutes</label><input type="number" name="convert_minutes" min="1" value="5"></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="button">Save access methods</button></div></form></div></div></div>
<div class="modal fade" id="stationModal" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="post" action="/admin/stations"><div class="modal-header"><div><h2 class="modal-title fs-5" id="stationModalTitle">Add hotspot station</h2><div class="small text-body-secondary">One station = one MikroTik Hotspot network. One Vendo may be linked separately.</div></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="_csrf" value="<?= e($csrf) ?>"><input type="hidden" name="action" value="create"><input type="hidden" name="id"><input type="hidden" name="router_id" value="<?= e($router['id']) ?>"><div class="row g-3"><div class="col-md-6"><label>Station name</label><input name="name" required></div><div class="col-md-6"><label>Portal theme</label><select name="portal_theme_id"><option value="0">Inherit gateway theme</option><?php foreach($themes as $theme):?><option value="<?= e($theme['id']) ?>"><?= e($theme['name']) ?></option><?php
endforeach;?></select></div><div class="col-md-6"><label>Hotspot server IP</label><input name="server_ip" required placeholder="10.0.3.1"></div><div class="col-md-6"><label>Client subnet</label><input name="client_subnet" placeholder="10.0.3.0/24"></div><div class="col-md-6"><label>Hotspot interface / bridge</label><input name="interface_name" placeholder="bridge-hotspot"></div><div class="col-md-6"><label>Password mode</label><select name="password_mode"><option value="blank">Blank password</option><option value="voucher">Voucher as password</option></select></div><div class="col-12"><label><input type="checkbox" name="enabled" value="1" checked> Enabled</label></div></div></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="button" id="station-submit">Add station</button></div></form></div></div></div>
<div class="modal fade" id="linkVendoModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post" action="/admin/vendo-gateway"><div class="modal-header"><div><h2 class="modal-title fs-5">Link Vendo</h2><div class="small text-body-secondary" id="link-vendo-station"></div></div><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="_csrf" value="<?= e($csrf) ?>"><input type="hidden" name="action" value="link_station"><input type="hidden" name="return_to" value="/admin/routers/<?= e($router['id']) ?>#stations"><input type="hidden" name="station_id"><label class="form-label">Vendo</label><select class="form-select" name="device_id"><option value="">Unlinked</option><?php foreach($gatewayVendos as $v):?><option value="<?= e($v['gateway_device_id']) ?>"><?= e($v['vendo_name']) ?><?= $v['station_name']?' — currently '.$v['station_name']:' — available' ?></option><?php
endforeach;?></select><div class="form-text mt-2">One station can have one Vendo. Choosing a Vendo already linked elsewhere moves it here. Any Vendo currently linked to this station becomes unlinked.</div></div><div class="modal-footer"><a class="btn btn-link me-auto" href="/admin/vendo-gateway">Manage Vendos</a><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save link</button></div></form></div></div></div>
<script>
const fm=document.getElementById('featuresModal');fm?.addEventListener('show.bs.modal',e=>{const b=e.relatedTarget,f=fm.querySelector('form'),d=JSON.parse(b.dataset.features||'{}');f.querySelector('[name=id]').value=b.dataset.id;document.getElementById('feature-station-name').textContent=b.dataset.name;f.querySelectorAll('[data-feature]').forEach(s=>{const v=d[s.dataset.feature]?.value;s.value=v===true?'on':v===false?'off':'inherit'});f.querySelector('[name=trial_minutes]').value=d.trial?.config?.minutes||10;f.querySelector('[name=convert_points]').value=d.points_convert?.config?.points||10;f.querySelector('[name=convert_minutes]').value=d.points_convert?.config?.minutes||5;});
const sm=document.getElementById('stationModal');sm?.addEventListener('show.bs.modal',e=>{const b=e.relatedTarget,edit=b?.dataset.mode==='edit',f=sm.querySelector('form');f.reset();f.querySelector('[name=router_id]').value='<?= e($router['id']) ?>';f.querySelector('[name=action]').value=edit?'update':'create';f.querySelector('[name=id]').value=edit?b.dataset.id:'';if(edit){f.querySelector('[name=name]').value=b.dataset.name;f.querySelector('[name=portal_theme_id]').value=b.dataset.theme;f.querySelector('[name=server_ip]').value=b.dataset.serverIp;f.querySelector('[name=client_subnet]').value=b.dataset.subnet;f.querySelector('[name=interface_name]').value=b.dataset.interface;f.querySelector('[name=password_mode]').value=b.dataset.passwordMode;f.querySelector('[name=enabled]').checked=b.dataset.enabled==='1'}document.getElementById('stationModalTitle').textContent=edit?'Edit hotspot station':'Add hotspot station';document.getElementById('station-submit').textContent=edit?'Save changes':'Add station';});
const lm=document.getElementById('linkVendoModal');lm?.addEventListener('show.bs.modal',e=>{const b=e.relatedTarget,f=lm.querySelector('form');f.querySelector('[name=station_id]').value=b.dataset.stationId;f.querySelector('[name=device_id]').value=b.dataset.deviceId||'';document.getElementById('link-vendo-station').textContent=b.dataset.stationName;});
</script>
<?php
endif;?>
